export const QUOTES: string[] = [
  "Suffering is the true test of life. — David Goggins",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
  "The impediment to action advances action. What stands in the way becomes the way. — Marcus Aurelius",
  "It is not the critic who counts; not the man who points out how the strong man stumbles. The credit belongs to the man who is actually in the arena. — Theodore Roosevelt",
  "Knowing is not enough, we must apply. Willing is not enough, we must do. — Bruce Lee",
  "He who has a why to live can bear almost any how. — Friedrich Nietzsche",
  "Hard times don't create heroes. It is during the hard times when the hero within us is revealed. — Bob Riley",
  "The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson",
  "No man is free who is not master of himself. — Epictetus",
  "Discipline equals freedom. — Jocko Willink",
  "The best way out is always through. — Robert Frost",
  "What we achieve inwardly will change outer reality. — Plutarch",
  "If you want to shine like the sun, first burn like the sun. — A. P. J. Abdul Kalam",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill",
  "In the middle of difficulty lies opportunity. — Albert Einstein",
  "The man who moves a mountain begins by carrying away small stones. — Confucius",
  "Strength does not come from winning. Your struggles develop your strengths. — Arnold Schwarzenegger",
  "Do not pray for an easy life; pray for the strength to endure a difficult one. — Bruce Lee",
  "The soul becomes dyed with the colour of its thoughts. — Marcus Aurelius",
  "A ship in harbour is safe, but that is not what ships are built for. — John A. Shedd",
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Turn your wounds into wisdom. — Oprah Winfrey",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
  "Act as if what you do makes a difference. It does. — William James",
  "You must be the change you wish to see in the world. — Mahatma Gandhi",
  "The unexamined life is not worth living. — Socrates",
  "Fall seven times, stand up eight. — Japanese Proverb",
  "I am not a product of my circumstances. I am a product of my decisions. — Stephen Covey",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "The mind is everything. What you think you become. — Buddha",
  "Happiness is not something ready-made. It comes from your own actions. — Dalai Lama",
  "Life is 10% what happens to you and 90% how you react to it. — Charles R. Swindoll",
  "The purpose of our lives is to be happy. — Dalai Lama",
  "You miss 100% of the shots you don't take. — Wayne Gretzky",
  "Whether you think you can or you think you can't, you're right. — Henry Ford",
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb",
  "An unexamined life is not worth living. — Socrates",
  "Your time is limited, don't waste it living someone else's life. — Steve Jobs",
  "If you look at what you have in life, you'll always have more. — Oprah Winfrey",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
  "Life is what happens when you're busy making other plans. — John Lennon",
  "The way to get started is to quit talking and begin doing. — Walt Disney",
  "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. — James Cameron",
  "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
  "It is during our darkest moments that we must focus to see the light. — Aristotle",
  "Whoever is happy will make others happy too. — Anne Frank",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. — Ralph Waldo Emerson",
  "Life is either a daring adventure or nothing at all. — Helen Keller",
  "Many of life's failures are people who did not realise how close they were to success when they gave up. — Thomas Edison",
  "The only impossible journey is the one you never begin. — Tony Robbins",
  "In this life we cannot do great things. We can only do small things with great love. — Mother Teresa",
  "If you really look closely, most overnight successes took a long time. — Steve Jobs",
  "The secret of getting ahead is getting started. — Mark Twain",
  "Don't judge each day by the harvest you reap but by the seeds that you plant. — Robert Louis Stevenson",
  "It is never too late to be what you might have been. — George Eliot",
  "Everything has beauty, but not everyone sees it. — Confucius",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world. — Anne Frank",
  "When I let go of what I am, I become what I might be. — Lao Tzu",
  "A person who never made a mistake never tried anything new. — Albert Einstein",
  "The only limit to our realisation of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. — Zig Ziglar",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
  "The best revenge is massive success. — Frank Sinatra",
  "Nothing is impossible, the word itself says I'm possible. — Audrey Hepburn",
  "The only way to discover the limits of the possible is to go beyond them into the impossible. — Arthur C. Clarke",
  "Well done is better than well said. — Benjamin Franklin",
  "What we fear doing most is usually what we most need to do. — Tim Ferriss",
  "The difficult is what takes a little time; the impossible is what takes a little longer. — Fridtjof Nansen",
  "A smooth sea never made a skilled sailor. — Franklin D. Roosevelt",
  "He who is not courageous enough to take risks will accomplish nothing in life. — Muhammad Ali",
  "You can never cross the ocean until you have the courage to lose sight of the shore. — Christopher Columbus",
  "I didn't get there by wishing for it or hoping for it, but by working for it. — Estée Lauder",
  "Perseverance is not a long race; it is many short races one after the other. — Walter Elliot",
  "It always seems impossible until it's done. — Nelson Mandela",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
  "Great things are done by a series of small things brought together. — Vincent van Gogh",
  "With the new day comes new strength and new thoughts. — Eleanor Roosevelt",
  "Quality is not an act, it is a habit. — Aristotle",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. — Thomas Edison",
  "Setting goals is the first step in turning the invisible into the visible. — Tony Robbins",
  "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
  "The only person you should try to be better than is the person you were yesterday. — Anonymous",
  "Courage is not the absence of fear, but the triumph over it. — Nelson Mandela",
  "If you can dream it, you can do it. — Walt Disney",
  "Don't count the days, make the days count. — Muhammad Ali",
  "The harder the conflict, the greater the triumph. — George Washington",
  "Only I can change my life. No one can do it for me. — Carol Burnett",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Ralph Waldo Emerson",
  "Where there is a will, there is a way. — English Proverb",
  "I think, therefore I am. — René Descartes",
  "Strive not to be a success, but rather to be of value. — Albert Einstein",
  "Work hard in silence, let your success be the noise. — Frank Ocean",
  "Dream big and dare to fail. — Norman Vaughan",
  "What does not kill me makes me stronger. — Friedrich Nietzsche",
  "Fortune favours the bold. — Virgil",
  "The pen is mightier than the sword. — Edward Bulwer-Lytton",
  "Knowledge is power. — Francis Bacon",
  "Lost time is never found again. — Benjamin Franklin",
  "Early to bed and early to rise makes a man healthy, wealthy, and wise. — Benjamin Franklin",
  "Genius is one percent inspiration and ninety-nine percent perspiration. — Thomas Edison",
  "There is nothing permanent except change. — Heraclitus",
  "Patience is bitter, but its fruit is sweet. — Jean-Jacques Rousseau",
  "The journey of a thousand miles begins with a single step. — Lao Tzu",
  "Doubt kills more dreams than failure ever will. — Suzy Kassem",
  "Everything you can imagine is real. — Pablo Picasso",
  "When something is important enough, you do it even if the odds are not in your favour. — Elon Musk",
  "Stay hungry, stay foolish. — Steve Jobs",
  "Try not to become a man of success. Rather become a man of value. — Albert Einstein",
  "You only live once, but if you do it right, once is enough. — Mae West",
  "To live is the rarest thing in the world. Most people exist, that is all. — Oscar Wilde",
  "Be the change that you wish to see in the world. — Mahatma Gandhi",
  "In three words I can sum up everything I've learned about life: it goes on. — Robert Frost",
  "If you tell the truth, you don't have to remember anything. — Mark Twain",
  "Always forgive your enemies; nothing annoys them so much. — Oscar Wilde",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. — Mahatma Gandhi",
  "That which does not kill us makes us stronger. — Friedrich Nietzsche",
  "I alone cannot change the world, but I can cast a stone across the waters to create many ripples. — Mother Teresa",
  "The world breaks everyone, and afterward, many are strong at the broken places. — Ernest Hemingway",
  "All that we are is the result of what we have thought. — Buddha",
  "No one can make you feel inferior without your consent. — Eleanor Roosevelt",
  "There is no greater agony than bearing an untold story inside you. — Maya Angelou",
  "I have learned over the years that when one's mind is made up, this diminishes fear. — Rosa Parks",
  "It is not length of life, but depth of life. — Ralph Waldo Emerson",
  "Life shrinks or expands in proportion to one's courage. — Anaïs Nin",
  "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self. — Ernest Hemingway",
  "The two most important days in your life are the day you are born and the day you find out why. — Mark Twain",
  "Not how long, but how well you have lived is the main thing. — Seneca",
  "We suffer more in imagination than in reality. — Seneca",
  "Luck is what happens when preparation meets opportunity. — Seneca",
  "The obstacle is the way. — Ryan Holiday",
  "He who fears he shall suffer, already suffers what he fears. — Michel de Montaigne",
  "Our life is what our thoughts make it. — Marcus Aurelius",
  "Dwell on the beauty of life. Watch the stars, and see yourself running with them. — Marcus Aurelius",
  "The best fighter is never angry. — Lao Tzu",
  "Mastering others is strength. Mastering yourself is true power. — Lao Tzu",
  "The wise warrior avoids the battle. — Sun Tzu",
  "Opportunities multiply as they are seized. — Sun Tzu",
  "We must all suffer one of two things: the pain of discipline or the pain of regret. — Jim Rohn",
  "Don't wish it were easier. Wish you were better. — Jim Rohn",
  "The successful warrior is the average man, with laser-like focus. — Bruce Lee",
  "Absorb what is useful, discard what is useless and add what is specifically your own. — Bruce Lee",
  "I hated every minute of training, but I said: don't quit. Suffer now and live the rest of your life as a champion. — Muhammad Ali",
  "Service to others is the rent you pay for your room here on earth. — Muhammad Ali",
  "Champions keep playing until they get it right. — Billie Jean King",
  "You have to expect things of yourself before you can do them. — Michael Jordan",
  "I've failed over and over and over again in my life. And that is why I succeed. — Michael Jordan",
  "The more I practice, the luckier I get. — Gary Player",
  "Tough times never last, but tough people do. — Robert H. Schuller",
  "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
  "The question isn't who is going to let me; it's who is going to stop me. — Ayn Rand",
  "If you want something you've never had, you must be willing to do something you've never done. — Thomas Jefferson",
  "People often say that motivation doesn't last. Well, neither does bathing — that's why we recommend it daily. — Zig Ziglar",
  "A champion is defined not by their wins but by how they can recover when they fall. — Serena Williams",
  "I have stood on a mountain of no's for one yes. — Barbara Elaine Smith",
  "Power is not given to you. You have to take it. — Beyoncé",
  "The most common way people give up their power is by thinking they don't have any. — Alice Walker",
  "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty. — Maya Angelou",
  "There is no passion to be found playing small — in settling for a life that is less than the one you are capable of living. — Nelson Mandela",
  "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. — Jamie Paolinetti",
  "Creativity is intelligence having fun. — Albert Einstein",
  "Logic will get you from A to B. Imagination will take you everywhere. — Albert Einstein",
  "The measure of intelligence is the ability to change. — Albert Einstein",
  "Imagination is more important than knowledge. — Albert Einstein",
  "Simplicity is the ultimate sophistication. — Leonardo da Vinci",
  "Learning never exhausts the mind. — Leonardo da Vinci",
  "I am still learning. — Michelangelo",
  "Every artist was first an amateur. — Ralph Waldo Emerson",
  "The earth has music for those who listen. — William Shakespeare",
  "All that glitters is not gold. — William Shakespeare",
  "This above all: to thine own self be true. — William Shakespeare",
  "We know what we are, but know not what we may be. — William Shakespeare",
  "Injustice anywhere is a threat to justice everywhere. — Martin Luther King Jr.",
  "Darkness cannot drive out darkness; only light can do that. — Martin Luther King Jr.",
  "The time is always right to do what is right. — Martin Luther King Jr.",
  "Faith is taking the first step even when you don't see the whole staircase. — Martin Luther King Jr.",
  "Not everything that is faced can be changed, but nothing can be changed until it is faced. — James Baldwin",
  "The price of anything is the amount of life you exchange for it. — Henry David Thoreau",
  "Go confidently in the direction of your dreams. Live the life you have imagined. — Henry David Thoreau",
  "Rather than love, than money, than fame, give me truth. — Henry David Thoreau",
  "Simplify, simplify. — Henry David Thoreau",
  "It is not the strongest of the species that survives, nor the most intelligent; it is the one most adaptable to change. — Charles Darwin",
  "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking. — Albert Einstein",
  "Peace cannot be kept by force; it can only be achieved by understanding. — Albert Einstein",
  "Reality is merely an illusion, albeit a very persistent one. — Albert Einstein",
  "Anyone who has never made a mistake has never tried anything new. — Albert Einstein",
  "Education is not the filling of a pail, but the lighting of a fire. — W.B. Yeats",
  "The roots of education are bitter, but the fruit is sweet. — Aristotle",
  "An investment in knowledge pays the best interest. — Benjamin Franklin",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn. — Benjamin Franklin",
  "Never leave that till tomorrow which you can do today. — Benjamin Franklin",
  "By failing to prepare, you are preparing to fail. — Benjamin Franklin",
  "Honesty is the first chapter in the book of wisdom. — Thomas Jefferson",
  "In matters of style, swim with the current; in matters of principle, stand like a rock. — Thomas Jefferson",
  "The only thing we have to fear is fear itself. — Franklin D. Roosevelt",
  "When you reach the end of your rope, tie a knot in it and hang on. — Franklin D. Roosevelt",
  "Speak softly and carry a big stick. — Theodore Roosevelt",
  "Do what you feel in your heart to be right — for you'll be criticised anyway. — Eleanor Roosevelt",
  "No one is useless in this world who lightens the burdens of another. — Charles Dickens",
  "Have a heart that never hardens, and a temper that never tires, and a touch that never hurts. — Charles Dickens",
  "It was the best of times, it was the worst of times. — Charles Dickens",
  "The secret of success is constancy to purpose. — Benjamin Disraeli",
  "One must still have chaos in oneself to be able to give birth to a dancing star. — Friedrich Nietzsche",
  "Without music, life would be a mistake. — Friedrich Nietzsche",
  "Whoever fights monsters should see to it that in the process he does not become a monster. — Friedrich Nietzsche",
  "Blessed is he who expects nothing, for he shall never be disappointed. — Alexander Pope",
  "To err is human; to forgive, divine. — Alexander Pope",
  "Hope springs eternal in the human breast. — Alexander Pope",
  "That which we persist in doing becomes easier to do, not that the nature of the thing has changed but that our power to do has increased. — Ralph Waldo Emerson",
  "The only way to have a friend is to be one. — Ralph Waldo Emerson",
  "What lies behind you and what lies in front of you pales in comparison to what lies inside of you. — Ralph Waldo Emerson",
  "For every minute you are angry you lose sixty seconds of happiness. — Ralph Waldo Emerson",
  "I destroy my enemies when I make them my friends. — Abraham Lincoln",
  "Nearly all men can stand adversity, but if you want to test a man's character, give him power. — Abraham Lincoln",
  "In the end, it's not the years in your life that count. It's the life in your years. — Abraham Lincoln",
  "Whatever you are, be a good one. — Abraham Lincoln",
  "Give me six hours to chop down a tree and I will spend the first four sharpening the axe. — Abraham Lincoln",
  "The best way to predict the future is to create it. — Peter Drucker",
  "Management is doing things right; leadership is doing the right things. — Peter Drucker",
  "Culture eats strategy for breakfast. — Peter Drucker",
  "A good plan violently executed now is better than a perfect plan executed next week. — George S. Patton",
  "If everybody is thinking alike, then somebody isn't thinking. — George S. Patton",
  "Courage is resistance to fear, mastery of fear — not absence of fear. — Mark Twain",
  "The man who does not read has no advantage over the man who cannot read. — Mark Twain",
  "Whenever you find yourself on the side of the majority, it is time to pause and reflect. — Mark Twain",
  "Keep your face always toward the sunshine — and shadows will fall behind you. — Walt Whitman",
  "Not I, nor anyone else can travel that road for you. You must travel it by yourself. — Walt Whitman",
  "I contain multitudes. — Walt Whitman",
  "The only true wisdom is in knowing you know nothing. — Socrates",
  "Strong minds discuss ideas, average minds discuss events, weak minds discuss people. — Socrates",
  "By all means marry; if you get a good wife, you'll become happy; if you get a bad one, you'll become a philosopher. — Socrates",
  "True knowledge exists in knowing that you know nothing. — Socrates",
  "Happiness depends upon ourselves. — Aristotle",
  "Knowing yourself is the beginning of all wisdom. — Aristotle",
  "The energy of the mind is the essence of life. — Aristotle",
  "It is the mark of an educated mind to be able to entertain a thought without accepting it. — Aristotle",
  "The only thing standing between you and your goal is the story you keep telling yourself. — Jordan Belfort",
  "A year from now you may wish you had started today. — Karen Lamb",
  "Don't be afraid to give up the good to go for the great. — John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. — Thomas Jefferson",
  "There are no shortcuts to any place worth going. — Beverly Sills",
  "The cost of being wrong is less than the cost of doing nothing. — Seth Godin",
  "If opportunity doesn't knock, build a door. — Milton Berle",
  "The way I see it, if you want the rainbow, you gotta put up with the rain. — Dolly Parton",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. — Jimmy Dean",
  "Perfection is not attainable, but if we chase perfection we can catch excellence. — Vince Lombardi",
  "Winners never quit, and quitters never win. — Vince Lombardi",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. — Vince Lombardi",
  "It's not whether you get knocked down, it's whether you get up. — Vince Lombardi",
  "The more you sweat in training, the less you bleed in combat. — Richard Marcinko",
  "Pain is temporary. Quitting lasts forever. — Lance Armstrong",
  "What the mind can conceive and believe, it can achieve. — Napoleon Hill",
  "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit. — Napoleon Hill",
  "Strength and growth come only through continuous effort and struggle. — Napoleon Hill",
  "Whatever the mind of man can conceive and believe, it can achieve. — Napoleon Hill",
  "The starting point of all achievement is desire. — Napoleon Hill",
  "You become what you think about most of the time. — Earl Nightingale",
  "Never give in, never give in, never, never, never — in nothing great or small. — Winston Churchill",
  "If you're going through hell, keep going. — Winston Churchill",
  "We make a living by what we get, but we make a life by what we give. — Winston Churchill",
  "Attitude is a little thing that makes a big difference. — Winston Churchill",
  "You will face many defeats in life, but never let yourself be defeated. — Maya Angelou",
  "If you don't like something, change it. If you can't change it, change your attitude. — Maya Angelou",
  "Nothing will work unless you do. — Maya Angelou",
  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. — Maya Angelou",
  "Try to be a rainbow in someone's cloud. — Maya Angelou",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier. — Mother Teresa",
  "If you judge people, you have no time to love them. — Mother Teresa",
  "Not all of us can do great things. But we can do small things with great love. — Mother Teresa",
  "Be faithful in small things because it is in them that your strength lies. — Mother Teresa",
  "Peace begins with a smile. — Mother Teresa",
  "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present. — Bill Keane",
  "The greatest wealth is to live content with little. — Plato",
  "Wise men speak because they have something to say; fools because they have to say something. — Plato",
  "Be kind, for everyone you meet is fighting a hard battle. — Plato",
  "Courage is knowing what not to fear. — Plato",
  "The measure of a man is what he does with power. — Plato",
  "Music gives a soul to the universe, wings to the mind, flight to the imagination, and life to everything. — Plato",
  "One of the penalties for refusing to participate in politics is that you end up being governed by your inferiors. — Plato",
  "The beginning is the most important part of the work. — Plato",
  "Don't let yesterday take up too much of today. — Will Rogers",
  "Even if you're on the right track, you'll get run over if you just sit there. — Will Rogers",
  "Life is not a problem to be solved, but a reality to be experienced. — Søren Kierkegaard",
  "Anxiety is the dizziness of freedom. — Søren Kierkegaard",
  "The function of prayer is not to influence God, but rather to change the nature of the one who prays. — Søren Kierkegaard",
  "People demand freedom of speech as a compensation for the freedom of thought which they seldom use. — Søren Kierkegaard",
  "Life must be understood backwards. But it must be lived forwards. — Søren Kierkegaard",
  "Knowing others is intelligence; knowing yourself is true wisdom. — Lao Tzu",
  "Nature does not hurry, yet everything is accomplished. — Lao Tzu",
  "A leader is best when people barely know he exists. — Lao Tzu",
  "Care about what other people think and you will always be their prisoner. — Lao Tzu",
  "He who conquers others is strong; he who conquers himself is mighty. — Lao Tzu",
  "If you correct your mind, the rest of your life will fall into place. — Lao Tzu",
  "The flame that burns twice as bright burns half as long. — Lao Tzu",
  "To see what is right and not do it is a lack of courage. — Confucius",
  "Real knowledge is to know the extent of one's ignorance. — Confucius",
  "Before you embark on a journey of revenge, dig two graves. — Confucius",
  "Our greatest glory is not in never falling, but in rising every time we fall. — Confucius",
  "Begin to be now what you will be hereafter. — William James",
  "The greatest weapon against stress is our ability to choose one thought over another. — William James",
  "If you want to be happy, be. — Leo Tolstoy",
  "Everyone thinks of changing the world, but no one thinks of changing himself. — Leo Tolstoy",
  "The two most powerful warriors are patience and time. — Leo Tolstoy",
  "In the depth of winter, I finally learned that within me there lay an invincible summer. — Albert Camus",
  "Shall I not have intelligence with the earth? Am I not partly leaves and vegetable mould myself? — Henry David Thoreau",
  "One should eat to live, not live to eat. — Molière",
  "Silence is the sleep that nourishes wisdom. — Francis Bacon",
  "He that hath patience can compass anything. — François Rabelais",
  "Beware the barrenness of a busy life. — Socrates",
  "If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things. — René Descartes",
  "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven. — John Milton",
  "To improve is to change; to be perfect is to change often. — Winston Churchill",
  "History will be kind to me for I intend to write it. — Winston Churchill",
  "Kites rise highest against the wind, not with it. — Winston Churchill",
  "Do the thing you fear to do and keep on doing it. That is the quickest and surest way to conquer fear. — Dale Carnegie",
  "Any fool can criticise, condemn, and complain — and most fools do. — Dale Carnegie",
  "Remember, today is the tomorrow you worried about yesterday. — Dale Carnegie",
  "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all. — Dale Carnegie",
  "Inaction breeds doubt and fear. Action breeds confidence and courage. — Dale Carnegie",
  "The world is a book, and those who do not travel read only one page. — Saint Augustine",
  "Habit, if not resisted, soon becomes necessity. — Saint Augustine",
  "The truth is like a lion; you don't have to defend it. Let it loose; it will defend itself. — Saint Augustine",
  "Be slow to fall into friendship; but when thou art in, continue firm and constant. — Socrates",
  "The greatest discovery of any generation is that a human being can alter his life by altering his attitude. — William James",
  "Adopt the pace of nature: her secret is patience. — Ralph Waldo Emerson",
  "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. — Leonardo da Vinci",
  "Time you enjoy wasting is not wasted time. — Marthe Troly-Curtin",
  "You don't have to see the whole staircase, just take the first step. — Martin Luther King Jr.",
  "Don't ask what the world needs. Ask what makes you come alive, and go do it. Because what the world needs is people who have come alive. — Howard Thurman",
  "What you do speaks so loudly that I cannot hear what you say. — Ralph Waldo Emerson",
  "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained. — Marie Curie",
  "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less. — Marie Curie",
  "Be less curious about people and more curious about ideas. — Marie Curie",
  "The most difficult thing is the decision to act, the rest is merely tenacity. — Amelia Earhart",
  "The best protection any woman can have is courage. — Elizabeth Cady Stanton",
  "I attribute my success to this: I never gave or took any excuse. — Florence Nightingale",
  "Well-behaved women seldom make history. — Laurel Thatcher Ulrich",
  "Above all, be the heroine of your life, not the victim. — Nora Ephron",
  "In order to be irreplaceable one must always be different. — Coco Chanel",
  "The most courageous act is still to think for yourself. Aloud. — Coco Chanel",
  "Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness. — Oprah Winfrey",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. — Joshua J. Marine",
  "If we did all the things we are capable of, we would literally astound ourselves. — Thomas Edison",
  "Vision without action is merely a dream. Action without vision just passes the time. Vision with action can change the world. — Joel A. Barker",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. — Aristotle",
  "Men's best successes come after their disappointments. — Henry Ward Beecher",
];

export const getDailyQuote = (dateStr: string): string => {
  const [year, month, day] = dateStr.split('-').map(Number);
  const epochDay = Math.floor(Date.UTC(year, month - 1, day) / 86400000);
  const index = ((epochDay % QUOTES.length) + QUOTES.length) % QUOTES.length;
  return QUOTES[index];
};
